package mario64

// Generated by :games:mario-n64:generateMario64ModelAssets
// Source: Bob-Omb Battlefield (Area1.dae)
// Render geometry lives only in the generated C world-mesh header. Keeping
// a second Kotlin copy made the N64 linker retain hundreds of kilobytes of
// unreachable software-renderer data. These constants preserve cheap JVM
// validation without adding runtime arrays to the ROM.
internal object Mario64ModelAssets {
    const val BATTLEFIELD_NAME = "Bob-Omb Battlefield"
    const val BATTLEFIELD_VERTEX_COUNT = 1623
    const val BATTLEFIELD_TRIANGLE_COUNT = 1100
    const val BATTLEFIELD_MATERIAL_COUNT = 18
    const val BATTLEFIELD_TEXTURE_COUNT = 18
    const val BATTLEFIELD_OPAQUE_MATERIAL_COUNT = 15
    const val BATTLEFIELD_MASKED_MATERIAL_COUNT = 2
    const val BATTLEFIELD_TRANSLUCENT_DECAL_MATERIAL_COUNT = 1
}
