import groovy.json.JsonSlurper
import java.awt.RenderingHints
import java.awt.image.BufferedImage
import java.io.ByteArrayInputStream
import java.io.File
import java.net.URLDecoder
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.util.Base64
import javax.imageio.ImageIO
import kotlin.math.roundToInt

private const val N64_TEXTURE_MAX_DIMENSION = 64
private const val N64_TEXTURE_MIN_DIMENSION = 8
private const val N64_VERTEX_CACHE_BUDGET = 512
private const val N64_TRIANGLE_FRAME_BUDGET = 96

data class N64DemoAssetPreflightSpec(
    val displayName: String,
    val assetFile: File,
    val sourceNote: String,
    val includeInDefaultRom: Boolean = false
)

data class N64DemoAssetBudgetReport(
    val displayName: String,
    val path: String,
    val sourceNote: String,
    val format: String,
    val meshCount: Int,
    val primitiveCount: Int,
    val vertexCount: Int,
    val triangleCount: Int,
    val materialCount: Int,
    val textureCount: Int,
    val imageCount: Int,
    val animationCount: Int,
    val skinCount: Int,
    val textureSources: List<N64DemoTextureSource>,
    val notes: List<String>
)

data class N64DemoTextureSource(
    val name: String,
    val sourceLabel: String,
    val sourceFile: File?,
    val bytes: ByteArray?,
    val mimeType: String?,
    val width: Int,
    val height: Int
) {
    val recommendedWidth: Int
        get() = recommendedN64TextureSize(width, height).first

    val recommendedHeight: Int
        get() = recommendedN64TextureSize(width, height).second

    val sourceRgba16Bytes: Int
        get() = width * height * 2

    val recommendedRgba16Bytes: Int
        get() = recommendedWidth * recommendedHeight * 2
}

private data class N64DemoObjBudgetStats(
    val vertexCount: Int,
    val triangleCount: Int,
    val materialCount: Int,
    val textureSources: List<N64DemoTextureSource>
)

private data class N64DemoGltfPayload(
    val root: Map<*, *>,
    val binaryChunk: ByteArray,
    val baseDir: File
)

private data class N64DemoTextureSourceCandidate(
    val sourceLabel: String,
    val sourceFile: File?,
    val bytes: ByteArray?
)

fun inspectN64DemoAssetBudget(
    spec: N64DemoAssetPreflightSpec,
    rootDir: File
): N64DemoAssetBudgetReport {
    val path = spec.assetFile.rootRelativePath(rootDir)
    if (!spec.assetFile.exists()) {
        return N64DemoAssetBudgetReport(
            displayName = spec.displayName,
            path = path,
            sourceNote = spec.sourceNote,
            format = "missing",
            meshCount = 0,
            primitiveCount = 0,
            vertexCount = 0,
            triangleCount = 0,
            materialCount = 0,
            textureCount = 0,
            imageCount = 0,
            animationCount = 0,
            skinCount = 0,
            textureSources = emptyList(),
            notes = listOf("asset was not found locally")
        )
    }

    return when (spec.assetFile.extension.lowercase()) {
        "obj" -> inspectN64DemoObjAssetBudget(spec, rootDir)
        "glb", "gltf" -> inspectN64DemoGltfAssetBudget(spec, rootDir)
        else -> N64DemoAssetBudgetReport(
            displayName = spec.displayName,
            path = path,
            sourceNote = spec.sourceNote,
            format = spec.assetFile.extension.ifBlank { "unknown" },
            meshCount = 0,
            primitiveCount = 0,
            vertexCount = 0,
            triangleCount = 0,
            materialCount = 0,
            textureCount = 0,
            imageCount = 0,
            animationCount = 0,
            skinCount = 0,
            textureSources = emptyList(),
            notes = listOf("format is not part of the current N64 preflight path")
        )
    }
}

fun renderN64DemoAssetBudgetReport(reports: List<N64DemoAssetBudgetReport>): String {
    return buildString {
        appendLine("# N64 Asset Preflight")
        appendLine()
        appendLine("Generated by `:games:n64-demo:preflightN64DemoAssets`.")
        appendLine("The default ROM still uses the redistributable Kenney fixtures; local Mario/Samus assets are inspected only as private compatibility benchmarks.")
        appendLine()
        appendLine("| Asset | Format | Vertices | Triangles | Materials | Textures | Largest texture | First concern |")
        appendLine("| --- | ---: | ---: | ---: | ---: | ---: | --- | --- |")
        reports.forEach { report ->
            appendLine(
                "| ${report.displayName.markdownCell()} | ${report.format.markdownCell()} | ${report.vertexCount} | " +
                    "${report.triangleCount} | ${report.materialCount} | ${report.textureCount} | " +
                    "${report.largestTextureSummary().markdownCell()} | ${report.notes.firstOrNull().orEmpty().markdownCell()} |"
            )
        }
        appendLine()

        reports.forEach { report ->
            appendLine("## ${report.displayName}")
            appendLine()
            appendLine("- Path: `${report.path}`")
            appendLine("- Source: ${report.sourceNote}")
            appendLine("- Geometry: ${report.meshCount} meshes, ${report.primitiveCount} primitives, ${report.vertexCount} vertices, ${report.triangleCount} triangles")
            appendLine("- Materials/textures: ${report.materialCount} materials, ${report.textureCount} texture refs, ${report.imageCount} images")
            if (report.animationCount > 0 || report.skinCount > 0) {
                appendLine("- Animation/skinning: ${report.animationCount} animations, ${report.skinCount} skins")
            }
            appendLine()
            if (report.textureSources.isNotEmpty()) {
                appendLine("| Texture | Source | Current | RGBA16 est. | N64 preview | Preview est. |")
                appendLine("| --- | --- | ---: | ---: | ---: | ---: |")
                report.textureSources.forEach { texture ->
                    appendLine(
                        "| ${texture.name.markdownCell()} | ${texture.sourceLabel.markdownCell()} | " +
                            "${texture.width}x${texture.height} | ${texture.sourceRgba16Bytes.formatBytes()} | " +
                            "${texture.recommendedWidth}x${texture.recommendedHeight} | ${texture.recommendedRgba16Bytes.formatBytes()} |"
                    )
                }
                appendLine()
            }
            if (report.notes.isNotEmpty()) {
                appendLine("Notes:")
                report.notes.forEach { note ->
                    appendLine("- $note")
                }
                appendLine()
            }
        }
    }.trimEnd() + System.lineSeparator()
}

fun writeN64DemoDownresTexturePreviews(
    reports: List<N64DemoAssetBudgetReport>,
    outputDir: File,
    projectDir: File
): File {
    outputDir.mkdirs()

    val manifest = mutableListOf<String>()
    manifest += "# N64 Down-Res Texture Preview"
    manifest += ""
    manifest += "Generated by `:games:n64-demo:downresN64DemoTextures`."
    manifest += ""

    reports.forEach { report ->
        val assetDir = File(outputDir, report.displayName.slugForFileName())
        assetDir.mkdirs()
        manifest += "## ${report.displayName}"
        if (report.textureSources.isEmpty()) {
            manifest += ""
            manifest += "No readable texture images found."
            manifest += ""
            return@forEach
        }

        manifest += ""
        report.textureSources.forEachIndexed { index, texture ->
            val sourceImage = texture.readBufferedImage() ?: return@forEachIndexed
            val downresImage = downresN64TexturePreview(
                image = sourceImage,
                width = texture.recommendedWidth,
                height = texture.recommendedHeight
            )
            val textureFile = File(
                assetDir,
                "${index.toString().padStart(2, '0')}-${texture.name.slugForFileName()}-" +
                    "${texture.recommendedWidth}x${texture.recommendedHeight}.png"
            )
            ImageIO.write(downresImage, "png", textureFile)
            manifest += "- `${texture.sourceLabel}` ${texture.width}x${texture.height} -> " +
                "`${textureFile.relativeTo(projectDir).invariantSeparatorsPath}` " +
                "${texture.recommendedWidth}x${texture.recommendedHeight}"
        }
        manifest += ""
    }

    val manifestFile = File(outputDir, "manifest.md")
    writeTextIfChanged(manifestFile, manifest.joinToString(System.lineSeparator()))
    return manifestFile
}

private fun inspectN64DemoObjAssetBudget(
    spec: N64DemoAssetPreflightSpec,
    rootDir: File
): N64DemoAssetBudgetReport {
    val stats = parseN64DemoObjBudgetStats(spec.assetFile, rootDir)
    return N64DemoAssetBudgetReport(
        displayName = spec.displayName,
        path = spec.assetFile.rootRelativePath(rootDir),
        sourceNote = spec.sourceNote,
        format = "obj",
        meshCount = if (stats.triangleCount > 0) 1 else 0,
        primitiveCount = if (stats.triangleCount > 0) 1 else 0,
        vertexCount = stats.vertexCount,
        triangleCount = stats.triangleCount,
        materialCount = stats.materialCount,
        textureCount = stats.textureSources.size,
        imageCount = stats.textureSources.size,
        animationCount = 0,
        skinCount = 0,
        textureSources = stats.textureSources,
        notes = n64BudgetNotes(
            vertexCount = stats.vertexCount,
            triangleCount = stats.triangleCount,
            textureSources = stats.textureSources,
            animationCount = 0,
            skinCount = 0,
            includeInDefaultRom = spec.includeInDefaultRom
        )
    )
}

private fun parseN64DemoObjBudgetStats(file: File, rootDir: File): N64DemoObjBudgetStats {
    var vertexCount = 0
    var triangleCount = 0
    val materials = linkedSetOf<String>()
    val materialFiles = mutableListOf<File>()

    file.forEachLine { rawLine ->
        val line = rawLine.trim()
        if (line.isEmpty() || line.startsWith("#")) return@forEachLine
        val parts = line.split(Regex("\\s+"))
        when (parts.firstOrNull()) {
            "v" -> if (parts.size >= 4) vertexCount += 1
            "f" -> {
                val faceVertexCount = parts.drop(1).count { token ->
                    parseObjVertexIndex(token, vertexCount) != null
                }
                if (faceVertexCount >= 3) {
                    triangleCount += faceVertexCount - 2
                }
            }
            "usemtl" -> parts.getOrNull(1)?.let(materials::add)
            "mtllib" -> {
                val materialPath = line.removePrefix("mtllib").trim()
                if (materialPath.isNotEmpty()) {
                    materialFiles += File(file.parentFile, materialPath)
                }
            }
        }
    }

    val textureSources = materialFiles
        .filter { it.exists() }
        .flatMap { parseN64DemoMtlTextureSources(it, rootDir) }
        .distinctBy { it.sourceLabel }

    return N64DemoObjBudgetStats(
        vertexCount = vertexCount,
        triangleCount = triangleCount,
        materialCount = materials.size,
        textureSources = textureSources
    )
}

private fun inspectN64DemoGltfAssetBudget(
    spec: N64DemoAssetPreflightSpec,
    rootDir: File
): N64DemoAssetBudgetReport {
    val payload = if (spec.assetFile.extension.lowercase() == "glb") {
        parseN64DemoGlbPayload(spec.assetFile, rootDir)
    } else {
        N64DemoGltfPayload(
            root = parseJsonObject(spec.assetFile.readText()),
            binaryChunk = ByteArray(0),
            baseDir = spec.assetFile.parentFile
        )
    }

    val root = payload.root
    val meshes = root.mapList("meshes")
    val accessors = root.mapList("accessors")
    val materials = root.mapList("materials")
    val textures = root.mapList("textures")
    val images = root.mapList("images")
    val animations = root.mapList("animations")
    val skins = root.mapList("skins")

    var primitiveCount = 0
    var vertexCount = 0
    var triangleCount = 0
    meshes.forEach { mesh ->
        val primitives = mesh.mapList("primitives")
        primitiveCount += primitives.size
        primitives.forEach { primitive ->
            val attributes = primitive["attributes"] as? Map<*, *>
            val positionAccessorIndex = attributes?.intValue("POSITION")
            val positionCount = positionAccessorIndex
                ?.let { accessors.getOrNull(it)?.intValue("count") }
                ?: 0
            vertexCount += positionCount

            val indexCount = primitive.intValue("indices")
                ?.let { accessors.getOrNull(it)?.intValue("count") }
            triangleCount += when {
                indexCount != null -> indexCount / 3
                positionCount > 0 -> positionCount / 3
                else -> 0
            }
        }
    }

    val textureSources = inspectN64DemoGltfTextureSources(payload, rootDir)

    return N64DemoAssetBudgetReport(
        displayName = spec.displayName,
        path = spec.assetFile.rootRelativePath(rootDir),
        sourceNote = spec.sourceNote,
        format = spec.assetFile.extension.lowercase(),
        meshCount = meshes.size,
        primitiveCount = primitiveCount,
        vertexCount = vertexCount,
        triangleCount = triangleCount,
        materialCount = materials.size,
        textureCount = textures.size,
        imageCount = images.size,
        animationCount = animations.size,
        skinCount = skins.size,
        textureSources = textureSources,
        notes = n64BudgetNotes(
            vertexCount = vertexCount,
            triangleCount = triangleCount,
            textureSources = textureSources,
            animationCount = animations.size,
            skinCount = skins.size,
            includeInDefaultRom = spec.includeInDefaultRom
        )
    )
}

private fun parseN64DemoGlbPayload(file: File, rootDir: File): N64DemoGltfPayload {
    val bytes = file.readBytes()
    require(bytes.size >= 20) { "GLB file is too short: ${file.rootRelativePath(rootDir)}" }

    val buffer = ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN)
    val magic = buffer.int
    require(magic == 0x46546C67) { "Invalid GLB magic for ${file.rootRelativePath(rootDir)}" }
    val version = buffer.int
    require(version == 2) { "Only GLB v2 is supported by N64 preflight: ${file.rootRelativePath(rootDir)}" }
    val declaredLength = buffer.int
    require(declaredLength <= bytes.size) { "GLB declared length exceeds file size: ${file.rootRelativePath(rootDir)}" }

    var json: String? = null
    var binaryChunk = ByteArray(0)
    while (buffer.position() + 8 <= declaredLength) {
        val chunkLength = buffer.int
        val chunkType = buffer.int
        val dataStart = buffer.position()
        val dataEnd = dataStart + chunkLength
        require(dataEnd <= declaredLength) { "Invalid GLB chunk length in ${file.rootRelativePath(rootDir)}" }

        when (chunkType) {
            0x4E4F534A -> json = bytes.decodeToString(dataStart, dataEnd).trim()
            0x004E4942 -> binaryChunk = bytes.copyOfRange(dataStart, dataEnd)
        }
        buffer.position(dataEnd)
    }

    return N64DemoGltfPayload(
        root = parseJsonObject(json ?: error("GLB has no JSON chunk: ${file.rootRelativePath(rootDir)}")),
        binaryChunk = binaryChunk,
        baseDir = file.parentFile
    )
}

private fun inspectN64DemoGltfTextureSources(
    payload: N64DemoGltfPayload,
    rootDir: File
): List<N64DemoTextureSource> {
    val images = payload.root.mapList("images")
    val bufferViews = payload.root.mapList("bufferViews")
    val textureSources = mutableListOf<N64DemoTextureSource>()

    images.forEachIndexed { index, image ->
        val name = image.stringValue("name")
            ?: image.stringValue("uri")?.substringAfterLast('/')
            ?: "image-$index"
        val mimeType = image.stringValue("mimeType")
        val uri = image.stringValue("uri")
        val source = when {
            uri != null && uri.startsWith("data:") -> {
                val bytes = parseDataUriBytes(uri)
                N64DemoTextureSourceCandidate(
                    sourceLabel = "embedded-data-uri:$name",
                    sourceFile = null,
                    bytes = bytes
                )
            }
            uri != null -> {
                val imageFile = File(payload.baseDir, decodeUriPath(uri))
                N64DemoTextureSourceCandidate(
                    sourceLabel = imageFile.rootRelativePath(rootDir),
                    sourceFile = imageFile,
                    bytes = null
                )
            }
            image.intValue("bufferView") != null -> {
                val bytes = extractN64DemoBufferViewBytes(
                    bufferViews = bufferViews,
                    bufferViewIndex = image.intValue("bufferView") ?: -1,
                    binaryChunk = payload.binaryChunk
                )
                N64DemoTextureSourceCandidate(
                    sourceLabel = "embedded-buffer-view:$index",
                    sourceFile = null,
                    bytes = bytes
                )
            }
            else -> null
        } ?: return@forEachIndexed

        val dimensions = readN64DemoImageDimensions(source.sourceFile, source.bytes) ?: return@forEachIndexed
        textureSources += N64DemoTextureSource(
            name = name,
            sourceLabel = source.sourceLabel,
            sourceFile = source.sourceFile,
            bytes = source.bytes,
            mimeType = mimeType,
            width = dimensions.first,
            height = dimensions.second
        )
    }

    return textureSources
}

private fun extractN64DemoBufferViewBytes(
    bufferViews: List<Map<*, *>>,
    bufferViewIndex: Int,
    binaryChunk: ByteArray
): ByteArray? {
    val view = bufferViews.getOrNull(bufferViewIndex) ?: return null
    val byteOffset = view.intValue("byteOffset") ?: 0
    val byteLength = view.intValue("byteLength") ?: return null
    val end = byteOffset + byteLength
    if (byteOffset < 0 || byteLength <= 0 || end > binaryChunk.size) return null
    return binaryChunk.copyOfRange(byteOffset, end)
}

private fun parseN64DemoMtlTextureSources(file: File, rootDir: File): List<N64DemoTextureSource> {
    val textures = mutableListOf<N64DemoTextureSource>()
    file.forEachLine { rawLine ->
        val line = rawLine.trim()
        if (line.isEmpty() || line.startsWith("#")) return@forEachLine
        val keyword = line.substringBefore(' ')
        if (keyword != "map_Kd" && keyword != "map_Ka" && keyword != "map_Ke") {
            return@forEachLine
        }

        val texturePath = line.substringAfter(' ', missingDelimiterValue = "").trim()
        if (texturePath.isEmpty()) return@forEachLine
        val textureFile = File(file.parentFile, texturePath)
        val dimensions = readN64DemoImageDimensions(textureFile, null) ?: return@forEachLine
        textures += N64DemoTextureSource(
            name = textureFile.nameWithoutExtension,
            sourceLabel = textureFile.rootRelativePath(rootDir),
            sourceFile = textureFile,
            bytes = null,
            mimeType = null,
            width = dimensions.first,
            height = dimensions.second
        )
    }
    return textures
}

private fun n64BudgetNotes(
    vertexCount: Int,
    triangleCount: Int,
    textureSources: List<N64DemoTextureSource>,
    animationCount: Int,
    skinCount: Int,
    includeInDefaultRom: Boolean
): List<String> {
    val notes = mutableListOf<String>()
    if (!includeInDefaultRom) {
        notes += "benchmark-only input; keep it out of committed/generated ROM data unless licensing is explicitly handled"
    }
    if (vertexCount > N64_VERTEX_CACHE_BUDGET) {
        notes += "exceeds the current N64 renderer projection cache of $N64_VERTEX_CACHE_BUDGET vertices; needs chunking or LOD"
    }
    if (triangleCount > N64_TRIANGLE_FRAME_BUDGET) {
        notes += "exceeds the current demo triangle budget of $N64_TRIANGLE_FRAME_BUDGET per frame; needs LOD, chunk selection, or occlusion"
    }
    if (textureSources.any { it.width > N64_TEXTURE_MAX_DIMENSION || it.height > N64_TEXTURE_MAX_DIMENSION }) {
        notes += "has textures larger than ${N64_TEXTURE_MAX_DIMENSION}px; run `downresN64DemoTextures` for previews"
    }
    if (animationCount > 0 || skinCount > 0) {
        notes += "contains animation/skinning data; current N64 demo path only consumes static baked geometry"
    }
    if (notes.isEmpty()) {
        notes += "fits the current static model budget envelope"
    }
    return notes
}

private fun N64DemoAssetBudgetReport.largestTextureSummary(): String {
    val texture = textureSources.maxByOrNull { it.width * it.height } ?: return "none"
    return "${texture.width}x${texture.height}"
}

private fun N64DemoTextureSource.readBufferedImage(): BufferedImage? {
    return when {
        sourceFile != null && sourceFile.exists() -> ImageIO.read(sourceFile)
        bytes != null -> ImageIO.read(ByteArrayInputStream(bytes))
        else -> null
    }
}

private fun downresN64TexturePreview(image: BufferedImage, width: Int, height: Int): BufferedImage {
    val scaled = BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB)
    val graphics = scaled.createGraphics()
    graphics.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_NEAREST_NEIGHBOR)
    graphics.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_SPEED)
    graphics.drawImage(image, 0, 0, width, height, null)
    graphics.dispose()
    return quantizeN64Rgba16Preview(scaled)
}

private fun quantizeN64Rgba16Preview(image: BufferedImage): BufferedImage {
    val output = BufferedImage(image.width, image.height, BufferedImage.TYPE_INT_ARGB)
    var y = 0
    while (y < image.height) {
        var x = 0
        while (x < image.width) {
            val argb = image.getRGB(x, y)
            val alpha = if (((argb ushr 24) and 0xff) >= 128) 255 else 0
            val red = quantizeN64Color5((argb ushr 16) and 0xff)
            val green = quantizeN64Color5((argb ushr 8) and 0xff)
            val blue = quantizeN64Color5(argb and 0xff)
            output.setRGB(x, y, (alpha shl 24) or (red shl 16) or (green shl 8) or blue)
            x += 1
        }
        y += 1
    }
    return output
}

private fun quantizeN64Color5(value: Int): Int {
    val level = ((value * 31) + 127) / 255
    return ((level * 255) + 15) / 31
}

private fun recommendedN64TextureSize(width: Int, height: Int): Pair<Int, Int> {
    if (width <= 0 || height <= 0) return N64_TEXTURE_MIN_DIMENSION to N64_TEXTURE_MIN_DIMENSION
    val scale = minOf(1.0, N64_TEXTURE_MAX_DIMENSION.toDouble() / maxOf(width, height).toDouble())
    val scaledWidth = maxOf(N64_TEXTURE_MIN_DIMENSION, (width * scale).roundToInt())
    val scaledHeight = maxOf(N64_TEXTURE_MIN_DIMENSION, (height * scale).roundToInt())
    return nearestN64TextureDimension(scaledWidth) to nearestN64TextureDimension(scaledHeight)
}

private fun nearestN64TextureDimension(value: Int): Int {
    var dimension = N64_TEXTURE_MIN_DIMENSION
    while (dimension * 2 <= value && dimension < N64_TEXTURE_MAX_DIMENSION) {
        dimension *= 2
    }
    return dimension.coerceIn(N64_TEXTURE_MIN_DIMENSION, N64_TEXTURE_MAX_DIMENSION)
}

private fun readN64DemoImageDimensions(file: File?, bytes: ByteArray?): Pair<Int, Int>? {
    val image = when {
        file != null && file.exists() -> ImageIO.read(file)
        bytes != null -> ImageIO.read(ByteArrayInputStream(bytes))
        else -> null
    } ?: return null
    return image.width to image.height
}

private fun parseJsonObject(json: String): Map<*, *> {
    return JsonSlurper().parseText(json) as? Map<*, *>
        ?: error("Expected a JSON object")
}

private fun parseDataUriBytes(uri: String): ByteArray? {
    val commaIndex = uri.indexOf(',')
    if (commaIndex < 0) return null
    val metadata = uri.substring(0, commaIndex)
    val payload = uri.substring(commaIndex + 1)
    return if (metadata.contains(";base64", ignoreCase = true)) {
        Base64.getDecoder().decode(payload)
    } else {
        URLDecoder.decode(payload, Charsets.UTF_8.name()).encodeToByteArray()
    }
}

private fun decodeUriPath(path: String): String {
    return URLDecoder.decode(path, Charsets.UTF_8.name())
}

private fun parseObjVertexIndex(token: String, vertexCount: Int): Int? {
    val rawIndex = token.substringBefore('/').toIntOrNull() ?: return null
    val zeroBased = if (rawIndex > 0) rawIndex - 1 else vertexCount + rawIndex
    return zeroBased.takeIf { it in 0 until vertexCount }
}

private fun Map<*, *>.mapList(key: String): List<Map<*, *>> {
    return (this[key] as? List<*>)
        ?.mapNotNull { it as? Map<*, *> }
        ?: emptyList()
}

private fun Map<*, *>.intValue(key: String): Int? {
    return (this[key] as? Number)?.toInt()
}

private fun Map<*, *>.stringValue(key: String): String? {
    return this[key] as? String
}

private fun File.rootRelativePath(rootDir: File): String {
    return try {
        relativeTo(rootDir).invariantSeparatorsPath
    } catch (_: IllegalArgumentException) {
        invariantSeparatorsPath
    }
}

private fun String.markdownCell(): String {
    return replace("|", "\\|").replace("\n", " ")
}

private fun Int.formatBytes(): String {
    return when {
        this >= 1024 * 1024 -> "${(this.toDouble() / (1024.0 * 1024.0)).roundToInt()} MiB"
        this >= 1024 -> "${(this.toDouble() / 1024.0).roundToInt()} KiB"
        else -> "$this B"
    }
}

private fun String.slugForFileName(): String {
    val slug = lowercase()
        .map { char ->
            when {
                char in 'a'..'z' -> char
                char in '0'..'9' -> char
                else -> '-'
            }
        }
        .joinToString("")
        .replace(Regex("-+"), "-")
        .trim('-')
    return slug.ifBlank { "asset" }
}

private fun writeTextIfChanged(file: File, text: String) {
    if (!file.exists() || file.readText() != text) {
        file.writeText(text)
    }
}
